apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-minio
  labels:
    app: aabs
    tier: minio
spec:
  serviceName: {{ .Release.Name }}-minio
  replicas: 1
  selector:
    matchLabels:
      app: aabs
      tier: minio
  template:
    metadata:
      labels:
        app: aabs
        tier: minio
    spec:
      containers:
      - name: minio
        image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
        imagePullPolicy: {{ .Values.minio.image.pullPolicy }}
        command: ["minio", "server", "/data", "--console-address", ":9001"]
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: console
        env:
        - name: MINIO_ROOT_USER
          value: "{{ .Values.minio.auth.rootUser }}"
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: MINIO_ROOT_PASSWORD
        resources:
          {{- toYaml .Values.minio.resources | nindent 10 }}
        volumeMounts:
        - name: miniodata
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: miniodata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.minio.storageSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-minio
  labels:
    app: aabs
    tier: minio
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: api
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: console
  selector:
    app: aabs
    tier: minio
