apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-qdrant
  labels:
    app: aabs
    tier: qdrant
spec:
  serviceName: {{ .Release.Name }}-qdrant
  replicas: 1
  selector:
    matchLabels:
      app: aabs
      tier: qdrant
  template:
    metadata:
      labels:
        app: aabs
        tier: qdrant
    spec:
      containers:
      - name: qdrant
        image: "{{ .Values.qdrant.image.repository }}:{{ .Values.qdrant.image.tag }}"
        imagePullPolicy: {{ .Values.qdrant.image.pullPolicy }}
        ports:
        - containerPort: 6333
          name: http
        - containerPort: 6334
          name: grpc
        resources:
          {{- toYaml .Values.qdrant.resources | nindent 10 }}
        volumeMounts:
        - name: qdrantdata
          mountPath: /qdrant/storage
        livenessProbe:
          httpGet:
            path: /health
            port: 6333
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 6333
          initialDelaySeconds: 5
          periodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: qdrantdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.qdrant.storageSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-qdrant
  labels:
    app: aabs
    tier: qdrant
spec:
  ports:
  - port: 6333
    targetPort: 6333
    protocol: TCP
    name: http
  - port: 6334
    targetPort: 6334
    protocol: TCP
    name: grpc
  selector:
    app: aabs
    tier: qdrant
